### Site Settings ###
title               : Roya Moussapour
description         : >-
                      UX researcher, customer experience strategist, data analyst, 
                      and emotional support human to a basset hound. 
baseurl             : ""          # figure out in description a better business angle: prioritization? impact? strategy?
  # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : yousinix/royamoussapour.github.io      # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : yousinix/portfolYOU
open_new_tab        : false                    # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md



### Author Info ###
author:
  name              : Roya Moussapour
  image             : https://i.imgur.com/eH4Oq4B.jpeg
    #https://i.imgur.com/XTjr5cg.jpeg
 # behance           : your_username
# dribbble          : your_username
  email             : roya.moussapour@gmail.com
  #facebook          : your_username
#  github            : your_username
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : roya-moussapour
 # medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
 # twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name



### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: G-02FEVZ7LFJ


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
